#Baseline com 0.30 de amostra

In [2]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.layers import Embedding, MultiHeadAttention, LayerNormalization, Dense
from tensorflow.keras.models import Model

data = pd.read_csv('../data/df_traduzido.csv').sample(frac=0.3)
data.head(3)

,Time_submitted,Review,Rating,Total_thumbsup,Reply,Review_Traduzida,Review_trazudida
5090,2022-06-28 11:52:08,7 ads in one go that's too much,1,0,NaN,NaN,"7 anúncios de uma vez só, isso é demais"
5386,2022-06-27 19:16:03,Love it easy to use...great selection of songs,4,0,NaN,NaN,"Adorei, fácil de usar...ótima seleção de músicas"
57328,2022-01-29 07:29:42,My app keeps crashing whenever I exit from the...,1,189,NaN,NaN,Meu aplicativo continua travando sempre que sa...

In [ ]:
data.drop(['Reply', 'Review_Traduzida'], axis=1, inplace=True)

In [ ]:
data.rename(columns={'Review_trazudida': 'Review_Traduzida'}, inplace=True)

In [ ]:
data.head(5)

,Time_submitted,Review,Rating,Total_thumbsup,Review_Traduzida
22713,2022-05-13 07:57:47,Nice app has many genres and can make your own...,5,0,O aplicativo legal tem muitos gêneros e você p...
50687,2022-02-21 11:01:11,I absolutely love Spotify it is great music Pl...,5,0,"Eu amo muito o Spotify, é uma ótima música. To..."
14827,2022-06-04 20:23:28,There are many things that the other apps lead...,4,18,Há muitas coisas que os outros aplicativos lid...
14149,2022-06-06 18:25:54,i can't play music on my samsung galaxy A10 al...,1,1,não consigo tocar música no meu samsung galaxy...
52928,2022-02-12 13:40:05,User interface nests too much. Hard to manage ...,1,0,A interface do usuário aninha muito. Difícil g...

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
            inputs, inputs, attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

In [ ]:
print(data.columns)

Index(['Time_submitted', 'Review', 'Rating', 'Total_thumbsup',
       'Review_Traduzida'],
      dtype='object')

In [ ]:
text_pairs = []

for line in data.itertuples(index=False):
    english = str(line.Review)  # Converter para string
    portugues = str(line.Review_Traduzida)  # Converter para string

    # Tratar valores ausentes ou NaN, substituindo por uma string vazia
    if pd.isna(portugues):
        portugues = ""

    portugues = "[start] " + portugues + " [end]"

    text_pairs.append((english, portugues))

In [ ]:
import random
print(random.choice(text_pairs))

random.shuffle(text_pairs)

num_val_samples = int(0.15 * len(text_pairs))
num_train_samples = len(text_pairs) - 2 * num_val_samples

train_pairs = text_pairs[:num_train_samples]
val_pairs = text_pairs[num_train_samples:num_train_samples + num_val_samples]
test_pairs = text_pairs[num_train_samples + num_val_samples:]

('Good. But it can only connect to my boom box for short time.', '[start] Bom. Mas ele só consegue se conectar ao meu aparelho de som por um curto período. [end]')

In [ ]:
type(train_pairs)

list

In [ ]:
import string
import re

strip_chars = string.punctuation + "¿"
strip_chars = strip_chars.replace("[", "")
strip_chars = strip_chars.replace("]", "")

def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

vocab_size = 15000
sequence_length = 30

source_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
)
target_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)

train_english_texts = [pair[0] for pair in train_pairs]
train_spanish_texts = [pair[1] for pair in train_pairs]
source_vectorization.adapt(train_english_texts)
target_vectorization.adapt(train_spanish_texts)

In [ ]:
batch_size = 64

def format_dataset(eng, pt):
    eng = source_vectorization(eng)
    pt = target_vectorization(pt)
    return ({
        "english": eng,
        "portugues": pt[:, :-1],
    }, pt[:, 1:])

def make_dataset(pairs):
    eng_texts, pt_texts = zip(*pairs)
    eng_texts = list(eng_texts)
    pt_texts = list(pt_texts)
    dataset = tf.data.Dataset.from_tensor_slices((eng_texts, pt_texts))
    dataset = dataset.batch(batch_size)
    dataset = dataset.map(format_dataset, num_parallel_calls=4)
    return dataset.shuffle(2048).prefetch(16).cache()

train_ds = make_dataset(train_pairs)
val_ds = make_dataset(val_pairs)

In [ ]:
for inputs, targets in train_ds.take(1):
    print(f"inputs['english'].shape: {inputs['english'].shape}")
    print(f"inputs['portugues'].shape: {inputs['portugues'].shape}")
    print(f"targets.shape: {targets.shape}")

inputs['english'].shape: (64, 30)
inputs['portugues'].shape: (64, 30)
targets.shape: (64, 30)

In [ ]:
class TransformerDecoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention_1 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.attention_2 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()
        self.layernorm_3 = layers.LayerNormalization()
        self.supports_masking = True

    def get_causal_attention_mask(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size, sequence_length = input_shape[0], input_shape[1]
        i = tf.range(sequence_length)[:, tf.newaxis]
        j = tf.range(sequence_length)
        mask = tf.cast(i >= j, dtype="int32")
        mask = tf.reshape(mask, (1, input_shape[1], input_shape[1]))
        mult = tf.concat(
            [tf.expand_dims(batch_size, -1),
             tf.constant([1, 1], dtype=tf.int32)], axis=0)
        return tf.tile(mask, mult)

    def call(self, inputs, encoder_outputs, mask=None):
        causal_mask = self.get_causal_attention_mask(inputs)
        if mask is not None:
            padding_mask = tf.cast(
                mask[:, tf.newaxis, :], dtype="int32")
            padding_mask = tf.minimum(padding_mask, causal_mask)
        else:
            padding_mask = mask
        attention_output_1 = self.attention_1(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=causal_mask)
        attention_output_1 = self.layernorm_1(inputs + attention_output_1)
        attention_output_2 = self.attention_2(
            query=attention_output_1,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=padding_mask,
        )
        attention_output_2 = self.layernorm_2(
            attention_output_1 + attention_output_2)
        proj_output = self.dense_proj(attention_output_2)
        return self.layernorm_3(attention_output_2 + proj_output)

class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.token_embeddings = layers.Embedding(
            input_dim=input_dim, output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    def get_config(self):
        config = super(PositionalEmbedding, self).get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

In [ ]:
embed_dim = 256
dense_dim = 2048
num_heads = 6

encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="english")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(encoder_inputs)
encoder_outputs = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="portugues")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(decoder_inputs)
x = TransformerDecoder(embed_dim, dense_dim, num_heads)(x, encoder_outputs)
x = layers.Dropout(0.5)(x)
decoder_outputs = layers.Dense(vocab_size, activation="softmax")(x)
transformer = keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

transformer.compile(
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

with tf.device('/device:GPU:0'):
    transformer.fit(train_ds, epochs=30, validation_data=val_ds)

Epoch 1/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 43s 137ms/step - accuracy: 0.3097 - loss: 5.2378 - val_accuracy: 0.3961 - val_loss: 3.6628
Epoch 2/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 16s 65ms/step - accuracy: 0.4046 - loss: 3.6025 - val_accuracy: 0.4353 - val_loss: 3.3440
Epoch 3/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 13s 66ms/step - accuracy: 0.4623 - loss: 3.1923 - val_accuracy: 0.5406 - val_loss: 2.7162
Epoch 4/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 21s 67ms/step - accuracy: 0.5669 - loss: 2.5618 - val_accuracy: 0.6034 - val_loss: 2.3348
Epoch 5/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 67ms/step - accuracy: 0.6206 - loss: 2.1905 - val_accuracy: 0.6375 - val_loss: 2.1183
Epoch 6/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 21s 67ms/step - accuracy: 0.6549 - loss: 1.9393 - val_accuracy: 0.6505 - val_loss: 2.0227
Epoch 7/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.6823 - loss: 1.7418 - val_accuracy: 0.6570 - val_loss: 1.9906
Epoch 8/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 65ms/step - accuracy: 0.7032 - loss: 1.5954 - val_accuracy: 0.6640 - val_loss: 1.9702
Epoch 9/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 21s 66ms/step - accuracy: 0.7219 - loss: 1.4623 - val_accuracy: 0.6617 - val_loss: 1.9681
Epoch 10/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 13s 65ms/step - accuracy: 0.7378 - loss: 1.3424 - val_accuracy: 0.6739 - val_loss: 1.9283
Epoch 11/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 13s 65ms/step - accuracy: 0.7528 - loss: 1.2414 - val_accuracy: 0.6771 - val_loss: 1.9305
Epoch 12/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 65ms/step - accuracy: 0.7692 - loss: 1.1435 - val_accuracy: 0.6789 - val_loss: 1.9355
Epoch 13/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.7803 - loss: 1.0597 - val_accuracy: 0.6753 - val_loss: 1.9789
Epoch 14/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 67ms/step - accuracy: 0.7929 - loss: 0.9800 - val_accuracy: 0.6804 - val_loss: 1.9881
Epoch 15/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 66ms/step - accuracy: 0.8066 - loss: 0.9010 - val_accuracy: 0.6818 - val_loss: 2.0188
Epoch 16/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 0.8168 - loss: 0.8368 - val_accuracy: 0.6756 - val_loss: 2.0772
Epoch 17/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 69ms/step - accuracy: 0.8270 - loss: 0.7755 - val_accuracy: 0.6802 - val_loss: 2.0804
Epoch 18/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.8372 - loss: 0.7215 - val_accuracy: 0.6766 - val_loss: 2.1555
Epoch 19/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 0.8470 - loss: 0.6655 - val_accuracy: 0.6787 - val_loss: 2.1554
Epoch 20/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.8591 - loss: 0.6096 - val_accuracy: 0.6857 - val_loss: 2.1629
Epoch 21/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 65ms/step - accuracy: 0.8701 - loss: 0.5591 - val_accuracy: 0.6838 - val_loss: 2.1943
Epoch 22/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.8766 - loss: 0.5217 - val_accuracy: 0.6810 - val_loss: 2.2400
Epoch 23/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.8856 - loss: 0.4788 - val_accuracy: 0.6761 - val_loss: 2.3591
Epoch 24/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 20s 67ms/step - accuracy: 0.8906 - loss: 0.4545 - val_accuracy: 0.6755 - val_loss: 2.3453
Epoch 25/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 21s 67ms/step - accuracy: 0.8987 - loss: 0.4181 - val_accuracy: 0.6815 - val_loss: 2.3536
Epoch 26/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.9056 - loss: 0.3877 - val_accuracy: 0.6819 - val_loss: 2.3724
Epoch 27/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 68ms/step - accuracy: 0.9105 - loss: 0.3617 - val_accuracy: 0.6818 - val_loss: 2.4129
Epoch 28/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 14s 67ms/step - accuracy: 0.9144 - loss: 0.3419 - val_accuracy: 0.6808 - val_loss: 2.4671
Epoch 29/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 15s 72ms/step - accuracy: 0.9202 - loss: 0.3162 - val_accuracy: 0.6811 - val_loss: 2.4802
Epoch 30/30
203/203 ━━━━━━━━━━━━━━━━━━━━ 13s 66ms/step - accuracy: 0.9253 - loss: 0.2948 - val_accuracy: 0.6839 - val_loss: 2.5121

In [ ]:
# Salvando para uso posterior
transformer.save('../modelos/20240903_modelo_transformer_tradutor_50epochs.keras')

In [ ]:
import numpy as np

pt_vocab = target_vectorization.get_vocabulary()
pt_index_lookup = dict(zip(range(len(pt_vocab)), pt_vocab))
max_decoded_sentence_length = 30

def decode_sequence(input_sentence):
    tokenized_input_sentence = source_vectorization([input_sentence])
    decoded_sentence = "[start]"

    for i in range(max_decoded_sentence_length):
        tokenized_target_sentence = target_vectorization(
            [decoded_sentence])[:, :-1]
        predictions = transformer([tokenized_input_sentence, tokenized_target_sentence])
        sampled_token_index = np.argmax(predictions[0, i, :])
        sampled_token = pt_index_lookup[sampled_token_index]
        decoded_sentence += " " + sampled_token

        if sampled_token == "[end]":
            break

    return decoded_sentence

In [ ]:
test_eng_texts = [pair[0] for pair in test_pairs]
for _ in range(30):
    input_sentence = random.choice(test_eng_texts)
    print("-")
    print(input_sentence)
    print(decode_sequence(input_sentence))

-
Excellent 👌... Good for burning calories....
[start] excelente 👌 bom para cima de gravar [end]
-
After having a premium family account for years, we're starting to be fed up with new issues. Recently, I lost the option to play certain Playlist at random or not. I can shuffle 2 of the 6 Playlist I made myself but not the others. At 16$ monthly, that's annoying.
[start] depois de ter uma conta familiar há anos passados para começar a usar problemas com a nova recentemente perdi a opção de reprodução certas playlists ou na sua playlist ou
-
I really like the app. However, the fact that you have to pay to listen to specific songs just bugs me. My parents won't pay for it, but some of the songs I like, such as Savage and Heart Attack, I have to go through playlists or find the song, put it into one of my playlists, and even then, I might not get to listen to it! So if you could change that, it would absolutely get you a 5 star rating, but until you change that, no way. Edit: Also, I agree with Gryffin Gurl
[start] eu realmente gosto do aplicativo mas o fato de você ter que pagar para ouvir músicas específicas apenas bugs que meus pais mas ele não me dá um pouco disso
-
Greatest app that iv,e ever came across hope everyone that listened to my site are all very happy that I'm back to continue my endevour thanks to all the people that have made it possible for a greater and better launch for all to appreciate and be happy all that had embraced and nutured for us to have become what we all wan't and wanted. Ahmad Aboucham And my team and all that contributed thank,s for everything.
[start] melhor aplicativo que já vi todos os tempos espero que ouvi todos são minha site estão muito feliz de volta o quotnão do meu carro obrigado o algum tempo todo
-
I have begun to have problems. Sometimes it just stops working. It used to work in background. Now it just stop when I name using another app. It never did this before. Dies anyone have the same problem? Do you have a solution? Peace
[start] tenho pausas espaço que às vezes ele simplesmente para de funcionar muito funcionar em segundo plano agora para que o nome quando abro o aplicativo ele nunca funcionou [end]
-
As long as you have Spotify premium this is the best app in the world!
[start] como de longo longo spotify premium o spotify é o melhor aplicativo é o melhor mundo [end]
-
I love how there are no commercials atheist I haven't heard any yet. I like it better than Pandora. Very easy to download what you want fast and easy.
[start] adoro como não há comerciais não tenho streaming que não ouço nenhum mas é melhor que o pandora melhor que o que você quer baixar e o fácil de ouvir
-
It won't even open it's just kept loading and loading
[start] ele nem abre é um pouco continuei carregando e carregamento simplesmente carrega [end]
-
The app as of the update on 27.04.22 : sucks. The option to slide to add to queue has been removed. The laggy startup has not been addressed; much less, fixed. The app crashed on multiple occasions. For the prices you charge, the app is far from good. Opening a playlist is glitchy and everything needs to load for long periods of time before displaying data. If you can't fix this app, leave it be as a free option. Make a seperate app for PREMIUM USERS because this is absurd.
[start] o aplicativo pois a atualização a opção de cuidado é uma droga não é possível deslizar o aplicativo tem sido o aplicativo pois a atualização então a opção de reprodução
-
Amazing music app 👌🏻👌🏻💕
[start] aplicativo de música incrível [end]
-
Still exploring but enjoying Spotify for the first time!
[start] ainda explorar mas não consigo passar o tempo [end]
-
App does not open correctly most of the time. Controls missing often. Stops when screen lock comes on often. Content is great but app experience is very very poor.
[start] o aplicativo não abre corretamente na maioria das vezes os controles do tempo frequentemente para na tela do som aparece quando o conteúdo está se a experiência é muito ruim
-
Hands down a great app with nearly every artist at your fingertips
[start] sem dúvida um ótimo aplicativo quase todos os artistas na ponta dos seus dedos [end]
-
I enjoy the selection of spiritual music very much😏
[start] gosto da seleção de músicas o ritmo o ritmo [end]
-
Love that I can make a playlist of my favorite songs and play them while on Facebook. Plus get reminders of the artist new releases on spotify.
[start] adoro que posso fazer uma playlist com minhas músicas favoritas e tocam enquanto toco no facebook em relação de forma de artista e faixas do spotify [end]
-
I dont know why but it wont let me play the songs i want? It plays like a 10/15 second demo but not the full song and when i play on my playlists it only lets me play shuffle AND IT FOESNT EVEN PLAY THR SONGSON MY ALBUM LMFAO!? it may just be a phone thing ad it works fine on my ipad thats all
[start] não sei por que mas não me deixa tocar as músicas que quero tocar como ele toca um segundo mas ele vai tocar a música e quando toco aleatoriamente e
-
I actually got so mad. It doesn't allow me to look at my playlists and when I try to play it, it doesn't show the '3 bar thing' so I can scroll to choose which one. I deleted and reinstalled it multiple times but it still wasn't working. Then I went offline and back online and it still didn't work.
[start] na verdade foi tão bravo para me permite que procuro e tocar quando tento tocar ela não toca o problema de 3 mostra a barra de 3 coisas que eu
-
Lot of bugs, One of them is when you remove (-) a song and press next(>) in playlist--- It skips next two songs and plays
[start] muitos bugs um pouco de uma música é quando você a próxima e então a próxima toca duas músicas e toca duas músicas [end]
-
Podcast is good & clear
[start] o podcast é bom e é bom [end]
-
Vere cofartable and very clear sound I like very much
[start] o recurso básico e com som muito claro [end]
-
With the last update, I can't skip a song anymore and Spotify stopped working 😭
[start] com a última atualização não consigo mais pular uma música e o spotify parou de funcionar 😭 [end]
-
Love Spotify's selection of music and Podcasts. I'm always discovering new artists. 5 star rating.
[start] adorei a seleção de músicas e podcasts sou sempre descobrindo novos artistas com 5 estrelas [end]
-
Spotify is the best app for music, but still way too basic for podcast. It lacks some important features like adding shows to a playlist. Not just episodes.
[start] o spotify é o melhor aplicativo para música mas ainda é muito básicos básicos algumas recursos básicos como alguns recursos como se não mostra uma lista de reprodução simplesmente não
-
Premium member who has high quality on and it is terrible audio on good speakers. Incomplete albums due to deleted content, missing songs not licensed or something. Amateur discography collections missing major works. App plays music not in a playlist despite having that option turned off as a premium member. Library page on phone is a mess due to previous listens. Finding playlists among many becomes a drag. App always bugging with popups during car. Works better on laptop, theres that.
[start] membro premium que tem de alta qualidade e a qualidade é terrível no áudio está as altofalantes inteligentesconectados devido a devido à perda de conteúdo ou não estão faltando o
-
I have been using paid version of spotify for quite a few years now and still love it!
[start] tenho usado a versão paga do spotify há algum anos e ainda é muito e ainda o amo [end]
-
Spotify knows algorithms! No more forced hip hop, Top 20, or r&b artists
[start] os algoritmos não são mais hip hop e hip hop de primeira e dos artistas [end]
-
You need to allow reporting ads. Some are VERY disturbing and disrupting.
[start] você precisa permitir que os anúncios são muito perturbador e alguns anúncios [end]
-
Excellent sound effect
[start] excelente o som efeito [end]
-
Spotify itself is ok, I'm having problems with blootooth,,so when playing in car,,,and I switch off car and walk to my front door, it starts playing on my phone, I've tried uninstall a few times,,switch off phone a few times,, but its still a problem,,seriously thinking of cancelling monthly subscription
[start] o spotify em si é ok estou com o cuidado o altofalante alexa o jogo 🎮 e desligo e o frente o meu frente está tocando no meu telefone o
-
Just a black screen when trying to start the app
[start] apenas uma tela preta quando tentando começar o aplicativo [end]

In [ ]:
#comentarios:
# REVIEW INVENTADA: 'Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium'
# REVIEW INVENTADA: 'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!'
# FRASE ALEATÓRIA QUE NÃO TEM SENTIDO : 'I love to eat Pizza, when is cold I drink wine'
# FRASE DA BASE TREINO: 'Unable to login .After this new update it shows error everytime I try to login

In [ ]:
reviews = ['Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium',
           'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!',
           'I love to eat pasta, when is cold I drink wine.',
           'Unable to login .After this new update it shows error everytime I try to login']

# Aplique a função decode_sequence para cada frase
for review in reviews:
    result = decode_sequence(review)
    print(result)

[start] o spotify tem uma seleção musical incrível mas os anúncios constantes e pulos limitados É limitado de usar o premium [end]
[start] Ótima qualidade de áudio mas continuo perdendo o controle ao volume ao transmitir para altofalante inteligente o meu altofalante realmente irritante [end]
[start] eu adoro o spoyify o ritmo é surreal quando o ritmo [end]
[start] não é possível fazer login depois dessa nova atualização ele mostra erro toda vez que tento fazer login [end]

#Modelo com ajustes - 60% de amostra
####com 0.60 de amostra, (para melhorar a generalização)
####com aumento do voca_size para 30mil (cobrir mais palavras e expressões)
####com sequence_length = 40 (capturar mais contexto em frases maiores)
####com num_heads = 12 (capturar melhor a relação entre as palavras)
####com dense_dim = 4096 (para capturar melhor os padrões)
####com layers.Dropout(0.7) (forçar melhor a generalização)
####com epochs=50 (melhorar o desempenho)
####com optimizer="adam" (mais estavel para modelos transformer)

Caso não funcione, próximo passo aumentar o embed_dim = 512
e adicionar o early_stop

In [5]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.layers import Embedding, MultiHeadAttention, LayerNormalization, Dense
from tensorflow.keras.models import Model

data = pd.read_csv('../data/df_traduzido.csv').sample(frac=0.6)
data.head(3)

,Time_submitted,Review,Rating,Total_thumbsup,Reply,Review_Traduzida,Review_trazudida
40182,2022-04-04 10:25:35,"It's trash without premium, I get not having s...",1,3,NaN,NaN,"É lixo sem premium, eu entendo não ter alguns ..."
7412,2022-06-23 03:11:50,I love this when I'm in a mood I have a Playli...,5,1,NaN,NaN,Eu adoro isso quando estou de mau humor. Tenho...
54514,2022-02-06 23:08:00,Good choices but after going thru all artists ...,3,0,NaN,NaN,"Boas escolhas, mas depois de passar por todos ..."

In [ ]:
data.drop(['Reply', 'Review_Traduzida'], axis=1, inplace=True)

In [ ]:
data.rename(columns={'Review_trazudida': 'Review_Traduzida'}, inplace=True)

In [ ]:
data.head(5)

,Time_submitted,Review,Rating,Total_thumbsup,Review_Traduzida
26082,2022-05-03 18:36:13,I've been using Spotify for Abt as long as I'v...,1,0,"Eu uso o Spotify há muito tempo, desde que com..."
46324,2022-03-08 19:11:23,It's not working at all It's not even liking t...,1,1,Não está funcionando de jeito nenhum. Nem esto...
35219,2022-04-15 01:02:43,Needs a version for chromebook. Using it on a ...,3,0,Precisa de uma versão para Chromebook. Usá-lo ...
36788,2022-04-13 13:31:34,Been having awful trouble lately with Spotify ...,1,0,Tenho tido problemas terríveis ultimamente com...
9628,2022-06-18 04:55:36,Just a W app. Helps with my workout routine 💪,5,0,Apenas um aplicativo W. Ajuda com minha rotina...

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
            inputs, inputs, attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

In [ ]:
print(data.columns)

Index(['Time_submitted', 'Review', 'Rating', 'Total_thumbsup',
       'Review_Traduzida'],
      dtype='object')

In [ ]:
text_pairs = []

for line in data.itertuples(index=False):
    english = str(line.Review)  # Converter para string
    portugues = str(line.Review_Traduzida)  # Converter para string

    # Tratar valores ausentes ou NaN, substituindo por uma string vazia
    if pd.isna(portugues):
        portugues = ""

    portugues = "[start] " + portugues + " [end]"

    text_pairs.append((english, portugues))

In [ ]:
import random
print(random.choice(text_pairs))

random.shuffle(text_pairs)

num_val_samples = int(0.15 * len(text_pairs))
num_train_samples = len(text_pairs) - 2 * num_val_samples

train_pairs = text_pairs[:num_train_samples]
val_pairs = text_pairs[num_train_samples:num_train_samples + num_val_samples]
test_pairs = text_pairs[num_train_samples + num_val_samples:]

('Would give 3 stars, if not for my history with this app. Please get it back to shape. Some design decisions are hard to understand, some technical aspects reminds rather an alpha version than long developed mature application. Let me give you 5 stars back again.', '[start] Daria 3 estrelas, se não fosse pelo meu histórico com este aplicativo. Por favor, coloque-o de volta em forma. Algumas decisões de design são difíceis de entender, alguns aspectos técnicos lembram mais uma versão alfa do que um aplicativo maduro desenvolvido há muito tempo. Deixe-me dar 5 estrelas de volta novamente. [end]')

In [ ]:
type(train_pairs)

list

In [ ]:
import string
import re

strip_chars = string.punctuation + "¿"
strip_chars = strip_chars.replace("[", "")
strip_chars = strip_chars.replace("]", "")

def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

vocab_size = 30000
sequence_length = 40

source_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
)
target_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)

train_english_texts = [pair[0] for pair in train_pairs]
train_spanish_texts = [pair[1] for pair in train_pairs]
source_vectorization.adapt(train_english_texts)
target_vectorization.adapt(train_spanish_texts)

In [ ]:
batch_size = 64

def format_dataset(eng, pt):
    eng = source_vectorization(eng)
    pt = target_vectorization(pt)
    return ({
        "english": eng,
        "portugues": pt[:, :-1],
    }, pt[:, 1:])

def make_dataset(pairs):
    eng_texts, pt_texts = zip(*pairs)
    eng_texts = list(eng_texts)
    pt_texts = list(pt_texts)
    dataset = tf.data.Dataset.from_tensor_slices((eng_texts, pt_texts))
    dataset = dataset.batch(batch_size)
    dataset = dataset.map(format_dataset, num_parallel_calls=4)
    return dataset.shuffle(2048).prefetch(16).cache()

train_ds = make_dataset(train_pairs)
val_ds = make_dataset(val_pairs)

In [ ]:
for inputs, targets in train_ds.take(1):
    print(f"inputs['english'].shape: {inputs['english'].shape}")
    print(f"inputs['portugues'].shape: {inputs['portugues'].shape}")
    print(f"targets.shape: {targets.shape}")

inputs['english'].shape: (64, 40)
inputs['portugues'].shape: (64, 40)
targets.shape: (64, 40)

In [ ]:
class TransformerDecoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention_1 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.attention_2 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()
        self.layernorm_3 = layers.LayerNormalization()
        self.supports_masking = True

    def get_causal_attention_mask(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size, sequence_length = input_shape[0], input_shape[1]
        i = tf.range(sequence_length)[:, tf.newaxis]
        j = tf.range(sequence_length)
        mask = tf.cast(i >= j, dtype="int32")
        mask = tf.reshape(mask, (1, input_shape[1], input_shape[1]))
        mult = tf.concat(
            [tf.expand_dims(batch_size, -1),
             tf.constant([1, 1], dtype=tf.int32)], axis=0)
        return tf.tile(mask, mult)

    def call(self, inputs, encoder_outputs, mask=None):
        causal_mask = self.get_causal_attention_mask(inputs)
        if mask is not None:
            padding_mask = tf.cast(
                mask[:, tf.newaxis, :], dtype="int32")
            padding_mask = tf.minimum(padding_mask, causal_mask)
        else:
            padding_mask = mask
        attention_output_1 = self.attention_1(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=causal_mask)
        attention_output_1 = self.layernorm_1(inputs + attention_output_1)
        attention_output_2 = self.attention_2(
            query=attention_output_1,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=padding_mask,
        )
        attention_output_2 = self.layernorm_2(
            attention_output_1 + attention_output_2)
        proj_output = self.dense_proj(attention_output_2)
        return self.layernorm_3(attention_output_2 + proj_output)

class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.token_embeddings = layers.Embedding(
            input_dim=input_dim, output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    def get_config(self):
        config = super(PositionalEmbedding, self).get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

In [ ]:
embed_dim = 256
dense_dim = 4096
num_heads = 12

encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="english")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(encoder_inputs)
encoder_outputs = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="portugues")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(decoder_inputs)
x = TransformerDecoder(embed_dim, dense_dim, num_heads)(x, encoder_outputs)
x = layers.Dropout(0.7)(x)
decoder_outputs = layers.Dense(vocab_size, activation="softmax")(x)
transformer = keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

transformer.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

with tf.device('/device:GPU:0'):
    transformer.fit(train_ds, epochs=50, validation_data=val_ds)

Epoch 1/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 101s 199ms/step - accuracy: 0.3568 - loss: 4.8937 - val_accuracy: 0.4089 - val_loss: 3.7776
Epoch 2/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 116s 162ms/step - accuracy: 0.4199 - loss: 3.7086 - val_accuracy: 0.4726 - val_loss: 3.1763
Epoch 3/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 161ms/step - accuracy: 0.4659 - loss: 3.2567 - val_accuracy: 0.4944 - val_loss: 2.9916
Epoch 4/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 81s 159ms/step - accuracy: 0.4887 - loss: 3.0552 - val_accuracy: 0.5126 - val_loss: 2.8426
Epoch 5/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 159ms/step - accuracy: 0.5112 - loss: 2.8758 - val_accuracy: 0.5458 - val_loss: 2.6399
Epoch 6/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.5417 - loss: 2.6627 - val_accuracy: 0.5782 - val_loss: 2.4369
Epoch 7/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 84s 159ms/step - accuracy: 0.5795 - loss: 2.4162 - val_accuracy: 0.6155 - val_loss: 2.2133
Epoch 8/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.6142 - loss: 2.1901 - val_accuracy: 0.6451 - val_loss: 2.0512
Epoch 9/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.6436 - loss: 1.9958 - val_accuracy: 0.6616 - val_loss: 1.9595
Epoch 10/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 159ms/step - accuracy: 0.6667 - loss: 1.8452 - val_accuracy: 0.6772 - val_loss: 1.8645
Epoch 11/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.6842 - loss: 1.7280 - val_accuracy: 0.6765 - val_loss: 1.9015
Epoch 12/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 62s 154ms/step - accuracy: 0.6954 - loss: 1.6471 - val_accuracy: 0.6951 - val_loss: 1.7706
Epoch 13/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 85s 162ms/step - accuracy: 0.7052 - loss: 1.5734 - val_accuracy: 0.6833 - val_loss: 1.8739
Epoch 14/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 80s 158ms/step - accuracy: 0.7190 - loss: 1.4771 - val_accuracy: 0.7064 - val_loss: 1.7370
Epoch 15/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 62s 154ms/step - accuracy: 0.7246 - loss: 1.4354 - val_accuracy: 0.7096 - val_loss: 1.7288
Epoch 16/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 156ms/step - accuracy: 0.7364 - loss: 1.3572 - val_accuracy: 0.7152 - val_loss: 1.7231
Epoch 17/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 158ms/step - accuracy: 0.7472 - loss: 1.2864 - val_accuracy: 0.7052 - val_loss: 1.8054
Epoch 18/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.7498 - loss: 1.2667 - val_accuracy: 0.7138 - val_loss: 1.7588
Epoch 19/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.7574 - loss: 1.2167 - val_accuracy: 0.7171 - val_loss: 1.7228
Epoch 20/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 158ms/step - accuracy: 0.7690 - loss: 1.1412 - val_accuracy: 0.7108 - val_loss: 1.7755
Epoch 21/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.7757 - loss: 1.0950 - val_accuracy: 0.7235 - val_loss: 1.7215
Epoch 22/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.7832 - loss: 1.0494 - val_accuracy: 0.7228 - val_loss: 1.7453
Epoch 23/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 159ms/step - accuracy: 0.7874 - loss: 1.0188 - val_accuracy: 0.7300 - val_loss: 1.7117
Epoch 24/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.7934 - loss: 0.9801 - val_accuracy: 0.7328 - val_loss: 1.7259
Epoch 25/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 157ms/step - accuracy: 0.8017 - loss: 0.9348 - val_accuracy: 0.7360 - val_loss: 1.7401
Epoch 26/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 156ms/step - accuracy: 0.8076 - loss: 0.8955 - val_accuracy: 0.7347 - val_loss: 1.7467
Epoch 27/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 159ms/step - accuracy: 0.8114 - loss: 0.8761 - val_accuracy: 0.7342 - val_loss: 1.7686
Epoch 28/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.8179 - loss: 0.8354 - val_accuracy: 0.7282 - val_loss: 1.8255
Epoch 29/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.8253 - loss: 0.7941 - val_accuracy: 0.7234 - val_loss: 1.8984
Epoch 30/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 154ms/step - accuracy: 0.8265 - loss: 0.7842 - val_accuracy: 0.7343 - val_loss: 1.7834
Epoch 31/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 84s 159ms/step - accuracy: 0.8263 - loss: 0.7873 - val_accuracy: 0.7368 - val_loss: 1.7675
Epoch 32/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 161ms/step - accuracy: 0.8337 - loss: 0.7451 - val_accuracy: 0.7409 - val_loss: 1.7551
Epoch 33/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 81s 158ms/step - accuracy: 0.8458 - loss: 0.6798 - val_accuracy: 0.7464 - val_loss: 1.7607
Epoch 34/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 157ms/step - accuracy: 0.8561 - loss: 0.6245 - val_accuracy: 0.7443 - val_loss: 1.8396
Epoch 35/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 159ms/step - accuracy: 0.8627 - loss: 0.5871 - val_accuracy: 0.7441 - val_loss: 1.8888
Epoch 36/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 156ms/step - accuracy: 0.8664 - loss: 0.5670 - val_accuracy: 0.7473 - val_loss: 1.8704
Epoch 37/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 156ms/step - accuracy: 0.8681 - loss: 0.5578 - val_accuracy: 0.7451 - val_loss: 1.8686
Epoch 38/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.8674 - loss: 0.5617 - val_accuracy: 0.7468 - val_loss: 1.8695
Epoch 39/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 85s 162ms/step - accuracy: 0.8666 - loss: 0.5676 - val_accuracy: 0.7363 - val_loss: 1.9438
Epoch 40/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.8678 - loss: 0.5619 - val_accuracy: 0.7384 - val_loss: 1.9258
Epoch 41/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 84s 159ms/step - accuracy: 0.8743 - loss: 0.5285 - val_accuracy: 0.7505 - val_loss: 1.9109
Epoch 42/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 83s 161ms/step - accuracy: 0.8824 - loss: 0.4856 - val_accuracy: 0.7520 - val_loss: 1.9393
Epoch 43/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 157ms/step - accuracy: 0.8900 - loss: 0.4483 - val_accuracy: 0.7505 - val_loss: 1.9740
Epoch 44/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 159ms/step - accuracy: 0.8938 - loss: 0.4264 - val_accuracy: 0.7498 - val_loss: 1.9863
Epoch 45/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 158ms/step - accuracy: 0.8970 - loss: 0.4135 - val_accuracy: 0.7483 - val_loss: 2.0081
Epoch 46/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 154ms/step - accuracy: 0.8988 - loss: 0.4047 - val_accuracy: 0.7471 - val_loss: 2.0398
Epoch 47/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 84s 159ms/step - accuracy: 0.9000 - loss: 0.3981 - val_accuracy: 0.7426 - val_loss: 2.0522
Epoch 48/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 64s 158ms/step - accuracy: 0.8997 - loss: 0.3989 - val_accuracy: 0.7277 - val_loss: 2.1885
Epoch 49/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 82s 159ms/step - accuracy: 0.8983 - loss: 0.4083 - val_accuracy: 0.7226 - val_loss: 2.2214
Epoch 50/50
405/405 ━━━━━━━━━━━━━━━━━━━━ 63s 155ms/step - accuracy: 0.8933 - loss: 0.4340 - val_accuracy: 0.7477 - val_loss: 2.0286

In [ ]:
# Salvando para uso posterior
transformer.save('../modelos/20240903_modelo_transformer_tradutor_50epochs.keras')

In [ ]:
import numpy as np

pt_vocab = target_vectorization.get_vocabulary()
pt_index_lookup = dict(zip(range(len(pt_vocab)), pt_vocab))
max_decoded_sentence_length = 40

def decode_sequence(input_sentence):
    tokenized_input_sentence = source_vectorization([input_sentence])
    decoded_sentence = "[start]"

    for i in range(max_decoded_sentence_length):
        tokenized_target_sentence = target_vectorization(
            [decoded_sentence])[:, :-1]
        predictions = transformer([tokenized_input_sentence, tokenized_target_sentence])
        sampled_token_index = np.argmax(predictions[0, i, :])
        sampled_token = pt_index_lookup[sampled_token_index]
        decoded_sentence += " " + sampled_token

        if sampled_token == "[end]":
            break

    return decoded_sentence

In [ ]:
test_eng_texts = [pair[0] for pair in test_pairs]
for _ in range(40):
    input_sentence = random.choice(test_eng_texts)
    print("-")
    print(input_sentence)
    print(decode_sequence(input_sentence))

-
No matter what mood your in, you can find the perfect song on Spotify.
[start] não importa qual o meu humor você pode encontrar a música perfeita no spotify [end]
-
Normally I enjoy Spotify, but recently it has been randomly closing on me while I'm using it. The service is great, but the app itself is not working well.
[start] normalmente gosto do spotify mas ultimamente ele tem sido forçado aleatoriamente me fechar enquanto estou usando o serviço é ótimo mas do aplicativo de si não está funcionando bem [end]
-
This app deserves more than 5 for me, all my old favourites came to bare. Great app it is...
[start] este aplicativo merece mais de 5 porque me forçou a usar [end]
-
In general the app is good, but recently when I play music it will occasionally not show the notification to show what song is playing or the app will freeze, I also can't unhide songs. Please fix these issues.
[start] no geral o aplicativo é bom mas recentemente quando toco música ele fica tocando ocasionalmente não mostra a notificação para qual música está tocando ou o aplicativo congela também não consigo ver essas músicas por favor consertem esses problemas [end]
-
♦️♦️♦️♦️♦️🎴DONT DOWNLOAD Bad app for misic it contains frequently ad 2:1RATIO OF ADS
[start] sensoring baixar aplicativo ruim para aproveitar com frequência sendo um anúncio curado [end]
-
It keeps cutting out after a few minutes. For some reason the dashboard that has the play and pause etc has disappeared.
[start] ele continua cortando depois de alguns minutos por algum motivo o sistema que tem a reprodução e os controles de reprodução desapareceram [end]
-
I don't know what has happened recently but it has been awful lately. Plays two songs at once, doesn't display what song is playing or allow you to skip songs. I don't know if there was a recent update but things have frustratingly hard the last while with this app.
[start] não sei o que aconteceu recentemente mas ele tem sido horrível ultimamente toca duas músicas sem tocar de vez não exibe qual música está tocando ou você não sabe que eu tinha mais músicas mas ele não estava lá isso
-
I love Spotify everything you want and more
[start] adoro o spotify tudo o que você quer mais [end]
-
Some time some songs aren't available also some times songs are playing but the song name and poster is not right .Sometime the network connection is Good but the app shows no network connection. Too much adds This app is the worst app don't install it .They only want money .
[start] algumas vezes algumas músicas não estão disponíveis nos últimos dias as músicas estão tocando mas a prévia da música escolhida é tocada às vezes a conexão é boa mas o aplicativo mostra que nenhuma conexão com a rede é muito
-
Loved my play lists until now, I can't click on a play button to start list or choose song on list to play!
[start] adorei minhas listas de reprodução até agora não consigo clicar em uma faixa tocar para começar a música escolher ou escolher na lista de reprodução para [end]
-
Great app but really needs to bring back the lock screen widget.
[start] Ótimo aplicativo mas realmente precisa ser baixado a tela de bloqueio no widget [end]
-
Please help I can't seem to get lyrics for any song,even after updating
[start] por favor ajude não consigo fazer as letras para nenhuma solicitação de avançado depois [end]
-
It was good until I powered off my phone. Now when I search up a song it just loads nothing else happens. And when I press play the song doesn't even play. I don't even know why this has happened. Fix this
[start] era bom até que eu atualizou meu telefone agora quando eu procuro uma música ele simplesmente carrega nada e quando eu volto a pressionar a música não toca a música nem sei por que isso aconteceu [end]
-
Been amazing so far. I haven't had to pay and there aren't ads? Um ok.
[start] foi incrível até agora não tive que pagar e há anúncios em todos os aspectos o quão tudo [end]
-
Duo doesn't work. Support didn't help much
[start] o duo não funciona o suporte não foi muito bloqueado [end]
-
Works great; love the selection. Hoping they continue to stand for freedom of content
[start] funciona muito bem adorei a seleção de ajuda eles a continuar implorando para joe rogan [end]
-
This app is good💜ther are all song thare bts blackpink song too🦋💜love is app 💜 💜 💜 💜 💜 💜
[start] este aplicativo está decaindo há todas as músicas de verdade bts blackpink seja aplicativo jeff cara cara 💜 💜 💜 [end]
-
Lots of content, but the app also has lots of bugs. At times it keeps playing in the background and the app cant be paused it just keeps playing until you close the app in the OS. Play/pause button disappears at least once a day also forcing close with OS is the only fix. Offline mode somehow still needs a data connection to launch the app... Also, downloaded content should be accessible from home screen direct and more prominent/visible.
[start] de muito conteúdo mas o aplicativo também tem muitos bugs às vezes ele continua tocando em segundo plano e o aplicativo não pode ser reproduzido por favor conserte o aplicativo em si desaparece o que o botão playpause desaparece desaparece
-
Easy to use. Great selection of music.
[start] fácil de usar ótima seleção de músicas [end]
-
Removed $2000 car radio feature from App. JVC, Kenwood, and Pioneere had built in apps on the car stereo that controlled Spotify while connected to phone via blutooth. This is not Car Play or Android Auto functionality, but a feature that just worked with a blutooth connection. Spotify drepicated this feature with the Feburary 1 2022 app update. Have to roll back to previous version to restore and prevent future Spotify app updates. VERY UPSET about this decision and am canceling my premium sub
[start] remova o recurso de rádio de faixa de rádio do aplicativo kenwood e fones cuidadosamente apagada no som de média no dispositivo que o spotify ao carregar enquanto conectado ao carro isso não é possível reproduzir a linha do carro
-
Plis upload some new songs. I m so excited.
[start] a criação de algumas músicas sou novo no gosto de estudar [end]
-
Always liked spotify but taking l down shows from JRE is not right.
[start] sempre gostei do spotify mas me falta de abrir o jre não é certo [end]
-
Just a heads up to the devs, my app is freezing. Not showing the little UI widget at the bottom when I select a song. The app won't even open yet it's playing sometimes. Only sometimes on that part. But the freezing is getting out of control.
[start] apenas um pouco de bom os desenvolvedores do meu aplicativo não está mostrando a pequena iu no telefone quando seleciono uma música de o aplicativo nem abre mas ele está tocando às vezes ele só toca a única parte mas
-
This app ain't working when I play a song it switches to songs that I hate so I want to give it a 0 but I need to give it a one
[start] este aplicativo não está funcionando quando toco uma música ele muda para músicas que eu odeio então dou uma e preciso dar uma e preciso delas [end]
-
It is a nice app but there is a problem that we can not download songs form it
[start] É um bom aplicativo mas tem um problema que não conseguimos baixar músicas de sua lista de reprodução ele [end]
-
i love Spotify but omg please fix your app lol. whenever I open it recently (z fold 2 oneui4.1) it just completely freezes up, forcing me to restart the app at minimum two times before it works. super frustrating and makes me hate using this app on mobile lately.
[start] eu adoro o spotify mas deus por favor conserte seu aplicativo lol eu sempre o abria recentemente atualizei 247 recentemente ela simplesmente trava para mim o aplicativo para ser reiniciado pelo menos 2 Às vezes antes ele funciona muito bem
-
Don't recommend, literally can't skip more than 6 songs for an entire hour, counting if you skip the random song that they recommend you even if you don't it.
[start] não recomendo literalmente não consigo pular mais de 6 músicas por hora inteira se você pular a música aleatórias que eles recomendam você nem se você não for [end]
-
Been a premium subscriber for years, worth every penny. A new album comes out and it just alerts you, very convenient, easy to use, always awesome
[start] sou assinante premium há anos vale cada centavo uma nova informação vem e só o removeram muito óbvia de usar o uso sempre [end]
-
I love everything about this app except the podcast experience. 5/5 for music, 2/5 for the podcasts and video interface. UPDATE, 18 Apr 2022: At some point in the last few weeks the app started to constantly crash and has become very buggy. I'm lowering the score until its fixed.
[start] adoro tudo sobre este aplicativo exceto a experiência do podcast em espanhol a hd para hd e atualização de vídeo atualização em computadores em um levol ele nos deu nos primeiros alguns meses o aplicativo começou a travar semanas e
-
Most terrible update ever. The last update just killed the app and it became a total mess from a used perspective. Playback stops, current song player bar dissapears etc... Awful update.
[start] a atualização mais terrível a atualização mais recente acabou de atualizar o aplicativo e ele se tornou uma bagunça total de reproduções na música frequentemente fica com a barra de reprodução desaparece etc atualização horrível [end]
-
I pay for this app and I'd rather listen to 3 homeless men screaming on the street, the "offline" doesn't work, and on stable wifi it doesn't know how to play a song half the time every on good wifi it crashes. It's a joke
[start] eu pago por esse aplicativo e prefiro ouvir 3 a 3 anos blackpink contra a verdade passada não está funcionando e no wifi ele não sabe como reproduzir uma música o mesmo tempo em todos os meus bons wifi em
-
Tired of redownloading my songs, over and over! Every stupid update and you need to reload, again.
[start] cansado de baixar minhas músicas mais de todos os tempos na atualização de alguma atualização estúpida e você precisa ajudar novamente [end]
-
Easy to find artiste and songs. Very good suggestions
[start] fácil de encontrar artistas e músicas muito boas sugestões [end]
-
I love it, but do think you should pay artist alot more then you do. You make billions. I love all the new artists that you can discover.
[start] eu adoro mas acho que você deveria pagar mais artistas do que você faz com que eu faça exatamente prometo o novo dos novos artistas que você pode descobrir [end]
-
The auto generated playlists and recommends are terrible. I miss a lot of podcasts because I don't get notifications that a new one is out and I am constantly skipping over songs because they are in my "for you" playlist but the songs are bad.
[start] as playlists geradas automaticamente e seriam terríveis eu acho que sinto falta de notificações porque não recebo uma nova um novo e estou constantemente pulando músicas constantemente por que eles estão na minha playlist você está tão ruim para você
-
There no adds u can turn your phone off and have it still playing and makes it louder
[start] não há anúncios você pode desligar seu telefone e ainda estou tocando e isso faz isso mais esforço [end]
-
It's not awful, but there are many ways Spotify can improve to compete with rising competition. I've heard praise for the app but it's a laggy, unintuitive mess for me, especially compared to my new service TIDAL. In addition, the quality is worse and the recommendations I got on Spotify were worse for me. Another point is how little Spotify pays artists compared to other services, Spotify pays 0.003 per stream vs Quobuz's 0.04$ per stream. I hope competition improves Spotify a bit!
[start] não é horrível mas há muitas maneiras de o spotify pode melhorar um wrap que falam sobre as viagens e é um pouco alto para atualizar meus diferentes ugh por favor meu novo serviço de família no tidal a forma
-
mostly the app is good no issue I have to faced but the problem is Lyrics just imrove it's very important thing that i found after this mostly everything is fine
[start] o aplicativo mais muito bom não é possível ter problemas eu procurei as letras mas o problema é que ele é muito importante que preciso dessa forma está além disso tudo está bem [end]
-
The perfect music app Without adds in premium
[start] o aplicativo de música perfeito sem anúncios no premium [end]
-
The progress bar won't even show up and the songs randomly stop after around a minute
[start] a barra de progresso não nem nem aparece e as músicas param aleatoriamente depois de um minuto [end]

In [ ]:
#comentarios:
# REVIEW INVENTADA: 'Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium'
# REVIEW INVENTADA: 'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!'
# FRASE ALEATÓRIA QUE NÃO TEM SENTIDO : 'I love to eat Pizza, when is cold I drink wine'
# FRASE DA BASE TREINO: 'Unable to login .After this new update it shows error everytime I try to login

In [ ]:
reviews = ['Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium',
           'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!',
           'I love to eat pasta, when is cold I drink wine.',
           'Unable to login .After this new update it shows error everytime I try to login']

# Aplique a função decode_sequence para cada frase
for review in reviews:
    result = decode_sequence(review)
    print(result)

[start] o spotify tem uma seleção musical incrível mas os anúncios são péssimos e pula repete as pulos para usar sem premium [end]
[start] Ótima qualidade de áudio mas continuo perdendo a controle via volume ao transmitir para meus fones de ouvido é realmente inconveniente [end]
[start] adoro chorar a conclusão é que quando eu aprimoro a músicasplaylists que [end]
[start] não consigo fazer login após a nova atualização ele mostra que o erro toda vez que tento fazer login [end]

# Modelo com ajustes - 100% dos dados

ajustes da última versão

embed_dim = 512
adicionar o early_stop

In [10]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.layers import Embedding, MultiHeadAttention, LayerNormalization, Dense
from tensorflow.keras.models import Model

data = pd.read_csv('../data/df_traduzido.csv')
data.head(3)

,Time_submitted,Review,Rating,Total_thumbsup,Reply,Review_Traduzida,Review_trazudida
0,2022-07-09 15:00:00,"Great music service, the audio is high quality...",5,2,NaN,"Ótimo serviço de música, o áudio é de alta qua...","Ótimo serviço de música, o áudio é de alta qua..."
1,2022-07-09 14:21:22,Please ignore previous negative rating. This a...,5,1,NaN,"Por favor, ignore a avaliação negativa anterio...","Por favor, ignore a avaliação negativa anterio..."
2,2022-07-09 13:27:32,"This pop-up ""Get the best Spotify experience o...",4,0,NaN,Este pop-up &quot;Obtenha a melhor experiência...,Este pop-up &quot;Obtenha a melhor experiência...

In [11]:
data.drop(['Reply', 'Review_Traduzida'], axis=1, inplace=True)

In [12]:
data.rename(columns={'Review_trazudida': 'Review_Traduzida'}, inplace=True)

In [13]:
data.head(5)

,Time_submitted,Review,Rating,Total_thumbsup,Review_Traduzida
0,2022-07-09 15:00:00,"Great music service, the audio is high quality...",5,2,"Ótimo serviço de música, o áudio é de alta qua..."
1,2022-07-09 14:21:22,Please ignore previous negative rating. This a...,5,1,"Por favor, ignore a avaliação negativa anterio..."
2,2022-07-09 13:27:32,"This pop-up ""Get the best Spotify experience o...",4,0,Este pop-up &quot;Obtenha a melhor experiência...
3,2022-07-09 13:26:45,Really buggy and terrible to use as of recently,1,1,Realmente cheio de bugs e terrível de usar ult...
4,2022-07-09 13:20:49,Dear Spotify why do I get songs that I didn't ...,1,1,"Caro Spotify, por que recebo músicas que não c..."

In [14]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

class TransformerEncoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()

    def call(self, inputs, mask=None):
        if mask is not None:
            mask = mask[:, tf.newaxis, :]
        attention_output = self.attention(
            inputs, inputs, attention_mask=mask)
        proj_input = self.layernorm_1(inputs + attention_output)
        proj_output = self.dense_proj(proj_input)
        return self.layernorm_2(proj_input + proj_output)

    def get_config(self):
        config = super().get_config()
        config.update({
            "embed_dim": self.embed_dim,
            "num_heads": self.num_heads,
            "dense_dim": self.dense_dim,
        })
        return config

In [15]:
print(data.columns)

Index(['Time_submitted', 'Review', 'Rating', 'Total_thumbsup',
       'Review_Traduzida'],
      dtype='object')

In [16]:
text_pairs = []

for line in data.itertuples(index=False):
    english = str(line.Review)  # Converter para string
    portugues = str(line.Review_Traduzida)  # Converter para string

    # Tratar valores ausentes ou NaN, substituindo por uma string vazia
    if pd.isna(portugues):
        portugues = ""

    portugues = "[start] " + portugues + " [end]"

    text_pairs.append((english, portugues))

In [17]:
import random
print(random.choice(text_pairs))

random.shuffle(text_pairs)

num_val_samples = int(0.15 * len(text_pairs))
num_train_samples = len(text_pairs) - 2 * num_val_samples

train_pairs = text_pairs[:num_train_samples]
val_pairs = text_pairs[num_train_samples:num_train_samples + num_val_samples]
test_pairs = text_pairs[num_train_samples + num_val_samples:]

("Let me disable podcasts on this app that I pay money for, I am NEVER going to listen to them yet they cover half the screen when I open the app. Why is something I've never so much as clicked on the second listing on the home page, right in the center of the screen? Edit 2/3/22 still annoyed by podcasts being in my way", '[start] Deixe-me desabilitar podcasts neste aplicativo pelo qual pago, NUNCA vou ouvi-los, mas eles cobrem metade da tela quando abro o aplicativo. Por que algo em que nunca cliquei está na segunda listagem na página inicial, bem no centro da tela? Editar 2/3/22 ainda estou incomodado com os podcasts que estão no meu caminho [end]')

In [18]:
type(train_pairs)

list

In [19]:
import string
import re

strip_chars = string.punctuation + "¿"
strip_chars = strip_chars.replace("[", "")
strip_chars = strip_chars.replace("]", "")

def custom_standardization(input_string):
    lowercase = tf.strings.lower(input_string)
    return tf.strings.regex_replace(
        lowercase, f"[{re.escape(strip_chars)}]", "")

vocab_size = 30000
sequence_length = 40

source_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length,
)
target_vectorization = layers.TextVectorization(
    max_tokens=vocab_size,
    output_mode="int",
    output_sequence_length=sequence_length + 1,
    standardize=custom_standardization,
)

train_english_texts = [pair[0] for pair in train_pairs]
train_spanish_texts = [pair[1] for pair in train_pairs]
source_vectorization.adapt(train_english_texts)
target_vectorization.adapt(train_spanish_texts)

In [20]:
batch_size = 64

def format_dataset(eng, pt):
    eng = source_vectorization(eng)
    pt = target_vectorization(pt)
    return ({
        "english": eng,
        "portugues": pt[:, :-1],
    }, pt[:, 1:])

def make_dataset(pairs):
    eng_texts, pt_texts = zip(*pairs)
    eng_texts = list(eng_texts)
    pt_texts = list(pt_texts)
    dataset = tf.data.Dataset.from_tensor_slices((eng_texts, pt_texts))
    dataset = dataset.batch(batch_size)
    dataset = dataset.map(format_dataset, num_parallel_calls=4)
    return dataset.shuffle(2048).prefetch(16).cache()

train_ds = make_dataset(train_pairs)
val_ds = make_dataset(val_pairs)

In [21]:
for inputs, targets in train_ds.take(1):
    print(f"inputs['english'].shape: {inputs['english'].shape}")
    print(f"inputs['portugues'].shape: {inputs['portugues'].shape}")
    print(f"targets.shape: {targets.shape}")

inputs['english'].shape: (64, 40)
inputs['portugues'].shape: (64, 40)
targets.shape: (64, 40)

In [22]:
class TransformerDecoder(layers.Layer):
    def __init__(self, embed_dim, dense_dim, num_heads, **kwargs):
        super().__init__(**kwargs)
        self.embed_dim = embed_dim
        self.dense_dim = dense_dim
        self.num_heads = num_heads
        self.attention_1 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.attention_2 = layers.MultiHeadAttention(
            num_heads=num_heads, key_dim=embed_dim)
        self.dense_proj = keras.Sequential(
            [layers.Dense(dense_dim, activation="relu"),
             layers.Dense(embed_dim),]
        )
        self.layernorm_1 = layers.LayerNormalization()
        self.layernorm_2 = layers.LayerNormalization()
        self.layernorm_3 = layers.LayerNormalization()
        self.supports_masking = True

    def get_causal_attention_mask(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size, sequence_length = input_shape[0], input_shape[1]
        i = tf.range(sequence_length)[:, tf.newaxis]
        j = tf.range(sequence_length)
        mask = tf.cast(i >= j, dtype="int32")
        mask = tf.reshape(mask, (1, input_shape[1], input_shape[1]))
        mult = tf.concat(
            [tf.expand_dims(batch_size, -1),
             tf.constant([1, 1], dtype=tf.int32)], axis=0)
        return tf.tile(mask, mult)

    def call(self, inputs, encoder_outputs, mask=None):
        causal_mask = self.get_causal_attention_mask(inputs)
        if mask is not None:
            padding_mask = tf.cast(
                mask[:, tf.newaxis, :], dtype="int32")
            padding_mask = tf.minimum(padding_mask, causal_mask)
        else:
            padding_mask = mask
        attention_output_1 = self.attention_1(
            query=inputs,
            value=inputs,
            key=inputs,
            attention_mask=causal_mask)
        attention_output_1 = self.layernorm_1(inputs + attention_output_1)
        attention_output_2 = self.attention_2(
            query=attention_output_1,
            value=encoder_outputs,
            key=encoder_outputs,
            attention_mask=padding_mask,
        )
        attention_output_2 = self.layernorm_2(
            attention_output_1 + attention_output_2)
        proj_output = self.dense_proj(attention_output_2)
        return self.layernorm_3(attention_output_2 + proj_output)

class PositionalEmbedding(layers.Layer):
    def __init__(self, sequence_length, input_dim, output_dim, **kwargs):
        super().__init__(**kwargs)
        self.token_embeddings = layers.Embedding(
            input_dim=input_dim, output_dim=output_dim)
        self.position_embeddings = layers.Embedding(
            input_dim=sequence_length, output_dim=output_dim)
        self.sequence_length = sequence_length
        self.input_dim = input_dim
        self.output_dim = output_dim

    def call(self, inputs):
        length = tf.shape(inputs)[-1]
        positions = tf.range(start=0, limit=length, delta=1)
        embedded_tokens = self.token_embeddings(inputs)
        embedded_positions = self.position_embeddings(positions)
        return embedded_tokens + embedded_positions

    def get_config(self):
        config = super(PositionalEmbedding, self).get_config()
        config.update({
            "output_dim": self.output_dim,
            "sequence_length": self.sequence_length,
            "input_dim": self.input_dim,
        })
        return config

In [23]:
from tensorflow.keras.callbacks import EarlyStopping

embed_dim = 512
dense_dim = 4096
num_heads = 12

encoder_inputs = keras.Input(shape=(None,), dtype="int64", name="english")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(encoder_inputs)
encoder_outputs = TransformerEncoder(embed_dim, dense_dim, num_heads)(x)

decoder_inputs = keras.Input(shape=(None,), dtype="int64", name="portugues")
x = PositionalEmbedding(sequence_length, vocab_size, embed_dim)(decoder_inputs)
x = TransformerDecoder(embed_dim, dense_dim, num_heads)(x, encoder_outputs)
x = layers.Dropout(0.7)(x)
decoder_outputs = layers.Dense(vocab_size, activation="softmax")(x)
transformer = keras.Model([encoder_inputs, decoder_inputs], decoder_outputs)

transformer.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"])

# Definindo EarlyStopping
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)
with tf.device('/device:GPU:0'):
    transformer.fit(train_ds, epochs=30, validation_data=val_ds)

Epoch 1/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 335s 462ms/step - accuracy: 0.3760 - loss: 4.3825 - val_accuracy: 0.4658 - val_loss: 3.2124
Epoch 2/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 452ms/step - accuracy: 0.4741 - loss: 3.1774 - val_accuracy: 0.5083 - val_loss: 2.8370
Epoch 3/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 304s 451ms/step - accuracy: 0.5109 - loss: 2.8413 - val_accuracy: 0.5404 - val_loss: 2.5869
Epoch 4/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.5434 - loss: 2.5856 - val_accuracy: 0.5673 - val_loss: 2.4180
Epoch 5/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.5729 - loss: 2.3827 - val_accuracy: 0.5905 - val_loss: 2.2765
Epoch 6/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 322s 453ms/step - accuracy: 0.6013 - loss: 2.1947 - val_accuracy: 0.6209 - val_loss: 2.1182
Epoch 7/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 452ms/step - accuracy: 0.6290 - loss: 2.0240 - val_accuracy: 0.6447 - val_loss: 1.9823
Epoch 8/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 306s 454ms/step - accuracy: 0.6538 - loss: 1.8622 - val_accuracy: 0.6632 - val_loss: 1.8874
Epoch 9/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 324s 481ms/step - accuracy: 0.6748 - loss: 1.7291 - val_accuracy: 0.6704 - val_loss: 1.8570
Epoch 10/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 363s 453ms/step - accuracy: 0.6968 - loss: 1.5910 - val_accuracy: 0.6904 - val_loss: 1.7448
Epoch 11/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 322s 454ms/step - accuracy: 0.7143 - loss: 1.4810 - val_accuracy: 0.7014 - val_loss: 1.6897
Epoch 12/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 340s 481ms/step - accuracy: 0.7322 - loss: 1.3649 - val_accuracy: 0.7209 - val_loss: 1.5974
Epoch 13/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 306s 455ms/step - accuracy: 0.7477 - loss: 1.2680 - val_accuracy: 0.7284 - val_loss: 1.5480
Epoch 14/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 340s 481ms/step - accuracy: 0.7605 - loss: 1.1888 - val_accuracy: 0.7363 - val_loss: 1.5213
Epoch 15/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 306s 454ms/step - accuracy: 0.7751 - loss: 1.0962 - val_accuracy: 0.7291 - val_loss: 1.5953
Epoch 16/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.7852 - loss: 1.0323 - val_accuracy: 0.7357 - val_loss: 1.5744
Epoch 17/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.7936 - loss: 0.9802 - val_accuracy: 0.7494 - val_loss: 1.4873
Epoch 18/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 304s 452ms/step - accuracy: 0.8014 - loss: 0.9332 - val_accuracy: 0.7476 - val_loss: 1.4980
Epoch 19/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.8108 - loss: 0.8772 - val_accuracy: 0.7506 - val_loss: 1.4877
Epoch 20/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.8204 - loss: 0.8206 - val_accuracy: 0.7553 - val_loss: 1.4753
Epoch 21/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.8296 - loss: 0.7651 - val_accuracy: 0.7580 - val_loss: 1.4937
Epoch 22/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 341s 481ms/step - accuracy: 0.8383 - loss: 0.7191 - val_accuracy: 0.7622 - val_loss: 1.4688
Epoch 23/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 382s 481ms/step - accuracy: 0.8427 - loss: 0.6892 - val_accuracy: 0.7600 - val_loss: 1.4863
Epoch 24/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 324s 481ms/step - accuracy: 0.8487 - loss: 0.6582 - val_accuracy: 0.7566 - val_loss: 1.5280
Epoch 25/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 364s 454ms/step - accuracy: 0.8544 - loss: 0.6273 - val_accuracy: 0.7574 - val_loss: 1.5356
Epoch 26/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 322s 454ms/step - accuracy: 0.8591 - loss: 0.6023 - val_accuracy: 0.7633 - val_loss: 1.5222
Epoch 27/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 322s 455ms/step - accuracy: 0.8635 - loss: 0.5784 - val_accuracy: 0.7658 - val_loss: 1.5337
Epoch 28/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 322s 454ms/step - accuracy: 0.8692 - loss: 0.5484 - val_accuracy: 0.7645 - val_loss: 1.5786
Epoch 29/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 321s 454ms/step - accuracy: 0.8741 - loss: 0.5241 - val_accuracy: 0.7683 - val_loss: 1.5392
Epoch 30/30
674/674 ━━━━━━━━━━━━━━━━━━━━ 305s 453ms/step - accuracy: 0.8782 - loss: 0.5003 - val_accuracy: 0.7666 - val_loss: 1.5694

In [28]:
# Salvando para uso posterior
transformer.save('../data/20240903_modelo_transformer_tradutor_30epochs.keras')

In [25]:
import numpy as np

pt_vocab = target_vectorization.get_vocabulary()
pt_index_lookup = dict(zip(range(len(pt_vocab)), pt_vocab))
max_decoded_sentence_length = 40

def decode_sequence(input_sentence):
    tokenized_input_sentence = source_vectorization([input_sentence])
    decoded_sentence = "[start]"

    for i in range(max_decoded_sentence_length):
        tokenized_target_sentence = target_vectorization(
            [decoded_sentence])[:, :-1]
        predictions = transformer([tokenized_input_sentence, tokenized_target_sentence])
        sampled_token_index = np.argmax(predictions[0, i, :])
        sampled_token = pt_index_lookup[sampled_token_index]
        decoded_sentence += " " + sampled_token

        if sampled_token == "[end]":
            break

    return decoded_sentence

In [26]:
test_eng_texts = [pair[0] for pair in test_pairs]
for _ in range(40):
    input_sentence = random.choice(test_eng_texts)
    print("-")
    print(input_sentence)
    print(decode_sequence(input_sentence))

-
Ever since the February 6 update the app has lost all car bluetooth functionality. No car controls, no song display and only occasionally will music play through the cars speakers. Getting real sick of paying for a premium service and having the developers not even bother fixing the problems. Do better Spotify.
[start] desde a primeiros 6 minutos o aplicativo perdeu o controle de transmissão a funcionalidade do car bluetooth não há controles de música para inesperadamente e apenas a música que toca no carro os dados ficam visíveis em um serviço premium
-
My downloads often get removed when I turn on my phone. Sometimes the playlist skips songs.
[start] meus downloads geralmente são removidas quando fecho quando ligo meu telefone Às vezes a playlist pula as músicas [end]
-
Really only good if you have money Listen, it's a good app when you actually have money. I'll give it that. But when you're unable to pay for a subscription things can get absolutely terrible. I'd be fine with like maybe an ad or two but no, free removes basically everything good about the app. It's terrible, like literally your strategy is making people so mad with the fre version they buy what the actual app should be without money. I'm legitimately considering changing music apps cuz of this
[start] sério só é bom se você tem dinheiro para ouvir é um bom aplicativo quando você realmente tem que pagar mas quando não pode pagar por uma assinatura pode ser terrível eu acho que terrível é uma coisa tão boa
-
I fell for fake news for hating spotify . I was wrong and i love joe rogan podcast . Thx fake news to introduce me to his podcast. The most reasonable autentic podcast . I wish we had a french canadian version of the joe rogan podcast. Someone step up plz.
[start] eu fiz para diferentes notícias ao longo do spotify fui lançado e adoro a joe rogan obrigado joe rogan em notícias do concorrente de mortal de entregar seus podcasts de aplicativos mais básicos eu queria que tivéssemos uma assinatura de
-
I love your stories I'm literally addicted to them... It brings me back to my childhood when I use to watch Are You Afraid of the Dark and when I use to read Goosebumps book. I appreciate this podcast ❤️
[start] eu amo seus histórias estou literalmente viciado em que ele me leva de volta ao meu relógio quando eu uso para assistir tempo 80 também baixe o escuro da apóstola of hostil ao usuário quando eu aprecio o podcast eu
-
Great Exp with Spotify!
[start] Ótimo aplicativo com o spotify [end]
-
I don't like how it shuffles the song because i wanna listen to my fav. song but it's shuffle, it's ok for me at ads
[start] não gosto de como ele embaralha a música que eu quero ouvir minha música favorita mas depois disso tudo está bem para mim com anúncios [end]
-
Spotify's worthy to my desires, adjusting my moody ways to levels much higher then prior! My only concerns are that I am a traditionalist! When I take time & effort to search for fav songs, SEE those selections on a Playlist, created by me, I'm anticipated to hear em all! Sure, alot depends on how your phone is setup and what service plan you have in order to store it, or better yet, to download it to your memory card. Ahh, my "worrie~free" life! Somebody's gotta du it! Ciao..
[start] o spotify merece meu quotconsoloquot no tempo as tecnologias ele cada dia a longo anos antes de fazer meu tempo de fazer isso estou pagando por um serviço que para pesquisar novas músicas curtidas as músicas curtidas tocam de uma
-
Really enjoy the mix of music
[start] gostei muito da mistura de música [end]
-
Animations are slow, album covers aren't loading, can't clear my search.
[start] animações falsas são menus e covers de faixas não estão carregando não é possível cantar [end]
-
Will not shut down and keeps running in the background,even when I force stop the app.Uninstalled.
[start] não desliga e continua travando no menu suspenso quando começo de parar o aplicativo [end]
-
It's so good for listening musics and podcasts
[start] É tão bom para ouvir músicas e podcasts [end]
-
Cannot use Spotify and Google maps at the same time.
[start] não consigo usar o spotify e o banco de dados de tempo na mesma hora [end]
-
Delivers the music I want but at the expence of artists who receive little revenue from this service! ☹️
[start] entrega a música que eu quero mas ao contrário dos artistas que recebo certos outros artistas que criaram [end]
-
Normally love Spotify but lots of bugs recently. Stops playing at random, doesn't give now playing option so can't pause, skip forward or back etc. Have updated to latest version and it didn't resolve it Edit: have premium account
[start] normalmente adoro o spotify mas muitos bugs recentemente para de tocar aleatoriamente não mostra nada tocando então não consigo pausar pular ou voltar etc tenho que atualizar para a versão mais recente e isso não resolve tem uma conta premium
-
Spotify is a good platform for music I have only one complain that they don't provide canvas in India every thing else is fine
[start] spotify é uma boa plataforma para música eu só tenho uma reclamação que eles colocam na sua tela inicial em vez de mais artistas é muito bom [end]
-
This app is garbage. It doesnt let you play the exact music you want to listen to. The rewind button is useless and you can only skip a few times. It's impossible to play songs from the playlist I created and only plays random songs that are not in the playlist.
[start] este aplicativo é lixo ele não deixa você tocar a música exata que quer ouvir para dormir é inútil e só pode pular algumas vezes você simplesmente toca algumas músicas da playlist eu criei o spotify e a playlist que
-
Having issues on all devices, apotyify just keeps stopping and starting again. It also doesn't have the menu where you can see what's playing that you can open for skipping, playing, ect.
[start] estou com problemas em todos os dispositivos que simplesmente param e começam de repente ele também não está lá você não tem o menu onde você está tocando o que pode abrir pular para tocar músicas etc [end]
-
This app is real fantastic but more than songs there are Ads. Should I listen ads or songs sometimes I think that is this song app or ads what should I do. But this app is really fantastic I love it. I think this app should have a award of (MOST ADS ARE IN THIS APP MORE THAN SONGS). There are only some ads are playing but whenever I play songs they play ads is there is compulsory to get premium. please try to understand in few few minutes they play ads
[start] este aplicativo é muito legal mas mais do que as músicas são anúncios eu deveria ouvir anúncios ou músicas Às vezes eu acho que é essa música ou o aplicativo spotify sem anúncios o que eu deveria muito fácil e
-
Yes, I am happy not paying for a subscription & understand that I will have ads. However, 2 and a half minutes of ads is over the top. Especially when I only hear 2 songs. 1 or 2 ads going for 10-15 seconds each every 2 or 3 songs is more than acceptable. Considering you let us hear an ad for 30 minutes of ad free music, that only works sometimes. Have lost count the amount of times I've listened to an ad to get the 30 minutes free only to have an ad 2 songs later...
[start] sim estou feliz não estou pagando por uma assinatura ouvimos anúncios no entanto 2 minutos no entanto 2 minutos de anúncios são longos no caso e só consigo pular 2 músicas 1 música 2 anúncios ou 3 músicas e depois
-
This app is so fun to use you tap it play the song you'd like to listen and thats it. I'm so glad spotify is an app, and really easy to use, though the ads are really annoying, I do wish you only get one ad and not like three ads in a row then the song you want to listen to but the app its self I really do enjoy.
[start] este aplicativo é muito divertido de usar você pode tocar a música que deseja tocar e isso é tão feliz e é estou tão feliz que o spotify é fácil de usar mas os anúncios são muito irritantes eu só
-
I've used Spotify exclusively for my music for over 10 years now. It's the best I can recommend. Free version on mobile kind of sucks - but premium isn't very expensive at all especially as a student.
[start] eu uso o spotify fielmente os dias para minha música por 10 anos agora é o melhor eu posso recomendar a versão para celular do celular principal não é caro mas o premium não é tão caro especialmente um desconto
-
I can't view lyrics and the scrollbar on Liked Songs can't be dragged! Previous versions has those features but on recent ones they removed it. I'm on android 11
[start] não consigo visualizar as letras e a barra de rolagem nas músicas curtidas não consigo encaminhar versões anteriores além disso os anúncios são reproduzidos recentemente o aplicativo se eles trouxessem de volta o android [end]
-
Hello, can you please make a feature where you can delete your recently played, the "Good morning" recommendation, and block episodes? i accidentally tapped something that isn't for me. and im uncomfortable with it.
[start] olá você pode por favor fazer um recurso onde você pode excluir sua audição recentemente recentemente os bons lançamentos musicais e episódios de podcast eu mal voltarei para mim e estou falando porque estou desconfortável [end]
-
App plays any song EXCEPT the one selected to play. This is useless; the PC and web versions are much better.
[start] o aplicativo toca qualquer música exceto a que é um incômodo selecionar para tocar isso a versões mais recentes e as versões são muito melhores [end]
-
I like this app. But recently why can't I select the song I like from an album?
[start] eu gosto deste aplicativo mas de novo por que não consigo baixar a música que gosto de um álbum [end]
-
Great Music App.
[start] Ótimo aplicativo de música [end]
-
All my saved song keeps on downloading everytime I open the app like what the hell is happening with the app I can't enjoy. Please fix it Spotify 🥺
[start] toda minha música salva uma música baixada continua baixando toda vez que abro o aplicativo como isso está acontecendo com o aplicativo não consigo gostar de por favor consertem o spotify 🥺 [end]
-
:( Bug that won't let me add any new personalized playlist photos. Says I should check my wifi connection. (which works perfectly fine.)
[start] bug que não me deixa mais tocar nenhuma nova música personalizada da lisa da faixa obscura não corresponde que estava tocando do meu telefone o que funciona bem [end]
-
Easy to find good music, old music I used to enjoy, new music I'm finding to love!🤩
[start] fácil de encontrar boa música antiga e música antiga que usei aproveite novas músicas que ouço alhamdulillah [end]
-
Language preference is poor. If I have selected the language as Tamil, why Hindi songs and playlists are popping up for me which I don't want to play. If you selected English as language and Spanish songs are getting recommended, how do you feel??
[start] a preferência é ruim se eu tiver selecionado as idiomas como a linguagem de trilha sonora de voz de formatura para mim por mim o que não quero ouvir se você seleciona se as faixas sugeridas e músicas aleatórias são
-
I've used Spotify for seven years I believe and the only issues I had were on my old phone when it would tell me my playlist wasn't downloaded when it was then when I got wifi again, it went back to saying it was downloaded. That's the only issues I've had.
[start] eu uso o spotify há sete anos acredito e o único problema que tive no meu telefone antigo quando ele me diz que minha playlist não estava online quando eu fui conectado e não tenho wifi de novo ele se
-
Everything I could ask for in a music app and more! I love it! Thank you.
[start] tudo o que eu poderia pedir em um aplicativo de música e muito mais eu adoro obrigado [end]
-
I'm finding a new place to listen to podcasts. I'm tired of some of the user experience and I hate some of the decisions they've made recently, so I've decided to listen elsewhere.
[start] estou encontrando um novo lugar para ouvir podcasts estou cansado de algumas da experiência do usuário e eu odeio algumas das reclamações eles fizeram isso recentemente então decidi ouvir em outro lugar [end]
-
Updated my Spotify now it does not ever let me log in to the account I'm paying for...
[start] atualizei meu spotify agora ele não me deixa fazer login na conta de uma conta que estou pagando por ele [end]
-
The random autoplay feature is pretty annoying. Where is that music coming from? Oh Spotify decided I needed to hear this grunged out folk music while I'm at the office. Keep paddling. There are banjos! I deleted the app for this reason.
[start] o recurso de reprodução automática de música é bem irritante onde está a música sai do spotify juro que o spotify decidiu que eu pediria para música offline enquanto estava no exterior mas parece estar indo ao possível do aplicativo
-
I have a lot of downloaded songs but now I can't listen to them, they aren't "available" even though it's downloaded. I can't listen offline. It used to be a really good app. It used to.
[start] tenho muitas músicas baixadas mas agora não consigo ouvir as marquei como estão disponíveis mesmo mesmo mesmo quando estão baixadas eu não consigo offline costumava ser um aplicativo muito bom [end]
-
I don't know what the hell happened but it's become insanely slow to open and glitchy all of a sudden. Fix this now.
[start] não sei o que diabos aconteceu mas ficou incrivelmente lento toda vez que eu abro e várias vezes para de repente isso acontece agora [end]
-
Changing my rating to 2 stars. Stupid app doesn't work on wifi. Says "No-Internet Connection Available" while I am connected to wifi and every other works just fine. Totally not worth paying for premium since you can't download songs over wifi. The only reason I gave 2 stars is bc the music still works as long as you can see it on the home page or in the library. Can't search for new songs or playlist tho.
[start] mudando minha classificação para 2 estrelas aplicativo idiota não funciona mais via wifi diz quotnenhuma conexão de internet disponívelquot enquanto estou conectado ao wifi e todas as outras vezes não vale a pena pagar pelo premium pois não é possível
-
Amazing the songs are amazing same with podcasts I wouldn't want any other music app
[start] incrível as músicas são incríveis a mesma coisa com podcasts eu não quero qualquer outro aplicativo de música [end]

In [ ]:
#comentarios:
# REVIEW INVENTADA: 'Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium'
# REVIEW INVENTADA: 'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!'
# FRASE ALEATÓRIA QUE NÃO TEM SENTIDO : 'I love to eat Pizza, when is cold I drink wine'
# FRASE DA BASE TREINO: 'Unable to login .After this new update it shows error everytime I try to login

In [27]:
reviews = ['Spotify has an amazing music selection, but the constant ads and limited skips make it frustrating to use without premium',
           'Great audio quality, but I keep losing control over the volume when casting to my smart speaker. Is really inconvenient!',
           'I love to eat pasta, when is cold I drink wine.',
           'Unable to login .After this new update it shows error everytime I try to login']

# Aplique a função decode_sequence para cada frase
for review in reviews:
    result = decode_sequence(review)
    print(result)

[start] o spotify tem uma seleção de músicas incrível mas os anúncios constantes e anúncios constantes para fazer ele é frustrante usar sem premium [end]
[start] Ótima qualidade de áudio mas continuo perdendo perco o controle sobre o volume ao transmitir para meu altofalante inteligente é muito inconveniente [end]
[start] adoro como sofri sem dúvida quando estamos pedalando a bicicleta para [end]
[start] não é possível fazer login após essa nova atualização ele mostra toda vez que tento fazer login [end]